[tool.poetry]
name = "cli-tools-lsp"
version = "0.1.0"
description = "Generic LSP to parse the output of CLI tools, linters, formatters, etc"
authors = ["Thomas Buckley-Houston <tom@tombh.co.uk>"]
license = "MIT"
readme = "README.md"
packages = [{include = "cli_tools_lsp"}]

[tool.poetry.dependencies]
python = "^3.10"
pygls = {path = "../pygls"}
parse = "^1.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
