name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  relase:
    name: "🚀 Release 🚢"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Python "3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Release
        run: |
          poetry build
          poetry publish --username "__token__" --password ${{ secrets.PYPI_API_TOKEN }}

